SSD/ISsdApi.cpp
SSD/SSD.vcxproj
SSD/SSD.vcxproj.filters

interface header 추가합니다. ISsApi.h 파일추가

<feature> ISsApi.h 파일추가

---

TestShell/TestShell.cpp
TestShell/TestShell.vcxproj
TestShell/TestShell.vcxproj.filters
TestShell/main.cpp

feat: TestShell 파일추가

---

SSD/SSD.vcxproj
SSD/SSD.vcxproj.filters
SSD/SsdTest.cpp
SSD/main.cpp

SSD에 executeCommand 부분 TC 추가 하였습니다.
1. 성공
2. 잘못된 커맨드 에러
3. LBA 범위 OutOfRange 에러
4. LBA 값 에러 1 (0~9, A~F)
5. LBA 값 앞 0x 에러
6. LBA 값 4byte 넘는 에러

<test> SSD executeCommand Test Code

---

TestShell/TestShell.cpp
TestShell/TestShell.vcxproj
TestShell/main.cpp

test: Debug read Test Case 추가했습니다.
pr 부탁드려요

test: Debug read Test Case 추가

---

TestShell/main.cpp

read test case 가 문제가 있었습니다. 
수정한 내용은 pr 부탁드립니다.
현재 상태로는 Build는 되지 않습니다.
- ssd mock 제작이 필요합니다.
- test Shell 에서 read 호출하면 ssd mock의 read가 3번 호출되어야 합니다.

read test case  01 수정 : ssd 3번 호출되는지 ---- pr 부탁드립니다.

---

SSD/ISsdApi.h
TestShell/TestShell.cpp
TestShell/main.cpp

- SSDMock 구현
- TC Pass 확인했습니다.

feat: TestShell excute 구현

---

SSD/SSD.vcxproj
SSD/Ssd.cpp
SSD/SsdTest.cpp
SSD/main.cpp

Main 함수 부분에 입력 받아서 Ssd로 넘기는 코드 작성 하였습니다.
생성자는 빌드시 오류나서 주석처리 하였으니 개발 부탁드립니다.

<feat> main argument read

---

TestShell/main.cpp

test case 3개 만들었습니다.
read 2개, write 1개 입니다.
mock 에 MOCK_METHOD가 필요할 것 같아요.

read 2개, write 1개 pr 부탁드립니다.

---

SSD/SsdTest.cpp
SSD/main.cpp

1. SsdFixture 추가 하여 Refactoring
2. Ssd Class 추가

<test> SSD Test Code Refactoring and Add Ssd Class Test

---

TestShell/TestShell.cpp
TestShell/main.cpp

pr 부탁드립니다.
TC 2개 추가하였습니다. 
read시 파일에서 읽어오는 내용을 추가하였습니다.

<test> TC 추가 : read 함수에서 파일에서 읽어오는 값 추가

---

SSD/SSD.vcxproj
SSD/SSD.vcxproj.filters
SSD/SsdTest.cpp
SSD/SsdTest.h

1. Mock class 내 commandResultTest 함수 추가
2. 실제 txt 파일 input, output 결과 read 함수 추가
3. Write & Read TC 4개 추가 (각각 ERROR, SUCCESS)

<test> MOCK Write & Read, Add TC

---

TestShell/TestShell.cpp
TestShell/main.cpp

exit 및 help구현 완료 - TC all Pass

<feat> exit 및 help구현 완료 - TC all Pass

---

TestShell/main.cpp

Invalid Command TC 추가하였습니다.
PR 부탁드려요.

<test> Test/test shell/tdd06 :  Invalid Command TC 추가

---

TestShell/main.cpp

TC를 잘못 만들었습니다.
수정하고 보완하였습니다.
PR 부탁드립니다.

<bug> Invalid Command로 수정, doNothing 추가

---

SSD/SsdTest.h
SSD/main.cpp

SSD Write Test Code에 문제가 있어 수정하였습니다!
TC All 정상 동작 됩니다.

<fix> SSD Write Test Code Fix

---

SSD/SSD.vcxproj
SSD/main.cpp

1. argument 방식 변경
2. release build path 변경

<fix> ssd argument input fix & release build path change

---

TestShell/main.cpp

fullwrite TC 추가하였습니다.
PR 부탁드립니다.

<test> add fullwrite TC 

---

TestShell/main.cpp

fullwrite & fullread TC 2개를 추가합니다
PR 부탁드립니다.

<test> add fullwrite & fullread

---

SSD/Command.cpp
SSD/Command.h
SSD/CommandFactory.cpp
SSD/CommandFactory.h
SSD/ReadCommand.cpp
SSD/ReadCommand.h
SSD/SSD.vcxproj
SSD/SSD.vcxproj.filters
SSD/Ssd.cpp
SSD/WriteCommand.cpp
SSD/WriteCommand.h

- read, write, command, factory

<refactoring> Command separate

---

SSD/Command.cpp
SSD/Command.h
SSD/CommandFactory.cpp
SSD/EraseCommand.cpp
SSD/EraseCommand.h
SSD/SSD.vcxproj
SSD/SSD.vcxproj.filters
SSD/main.cpp

<feature> Erase command Impl.

---

TestShell/main.cpp

PR 부탁드립니다. 
조건문 부호에 오류가 있었습니다.

<bugfix> parcing 부호 오류 해결

---

SSD/CommandBuffer.cpp
SSD/CommandBuffer.h
SSD/SSD.vcxproj
SSD/SSD.vcxproj.filters
SSD/Ssd.cpp

- class 및 buffer 용 파일과 폴더 추가
- 1차 코드로 2차로는 command 처리 순서 변동과 command 객체에서 수행하는 것을 분리 예정입니다.
- 요구사항 문서,  ssd 기능 수행 순서 탭에서 정리중이니 참고해주세요
- (https://docs.google.com/spreadsheets/d/1pwXhmDBLAZRIh__p33HfTzaVxB62uD-8J9q_RE6NiRI/edit?usp=drive_link)

<feature> Command Buffer 구현

---

TestScript/TestSuite.cpp

Test Script 2번 3번 Case 추가하였습니다.

<feat> Add Test Script Case

---

TestShell/TestShell.cpp

PR 요청합니다. 
Test Scenario 2, 3 완료하였습니다.

<feat> Test Scenario 2, 3 추가

---

SSD/SSD.vcxproj
TestShell/TestShell.cpp
TestShell/TestShell.vcxproj

1) Erase 구현 했습니다.
2) 현재는 cout 으로 SSD 임시로 호출하고 있어요.

<feature> erase구현

---

TestShell/TestShell.cpp

<feature> flush 구현

---

TestScript/FullWriteAndReadCompareCommand.cpp
TestScript/FullWriteAndReadCompareCommand.h
TestScript/ITestCommand.h
TestScript/TestCommandFactory.cpp
TestScript/TestCommandFactory.h
TestScript/TestScript.vcxproj
TestScript/TestScript.vcxproj.filters
TestScript/TestSuite.cpp
TestScript/TestUtils.cpp
TestScript/TestUtils.h

디자인 패턴 Command Pattern 으로 Test Script dll refactoring 진행 하였습니다.
Case 1 대상으로 일단 진행하였고
Case 2, 3 추가 예정입니다.

<refac> Test Script Refactoring

---

TestShell/TestShell.cpp
TestShell/TestShell.vcxproj
TestShell/main.cpp

PR 요청드립니다.
tset Shell refac 맞춤으로 debug 모드 TC 변경 건 입니다.

<fix> test Shell Refactoring에 맞춤 Fix

---

TestShell/Logger.cpp
TestShell/TestShell.cpp
TestShell/TestShell.vcxproj
TestShell/TestShell.vcxproj.filters

1) Logger Class 생성했습니다.
2) txt 파일에 Logging 은 추가되지만, 특정 사이즈 이상이 되면 파일 이름 변경 및 Zip추가 기능은 아직 동작하지 않습니다.
3) TestShell 리팩토링 이후 Logging 추가 예정입니다.

<featrue> Logger 추가

---

TestShell/TestShell.cpp

PR 요청드립니다. 
TC 4 추가하였습니다. 결과는 PASS 입니다. 
단, test 시간이 엄청 걸립니다.

<feature> TC 4 erase Range 추가

---

TestShell/Logger.cpp

<feature> Logger 기능 구현 완료

---

TestScript/EraseAndWriteAging.cpp
TestScript/EraseAndWriteAging.h
TestScript/TestCommandFactory.cpp
TestScript/TestScript.vcxproj
TestScript/TestScript.vcxproj.filters
TestScript/TestSuite.cpp
TestScript/TestUtils.cpp
TestScript/TestUtils.h

<feat> Add Test Script Case 4

---

TestScript/TestCommandFactory.cpp
TestScript/TestSuite.cpp
TestShell/Logger.cpp
TestShell/TestShell.cpp
TestShell/main.cpp

PR 요청드립니다.
Runner DLL Integration 및 Test 완료하였습니다.
추가로 로거 파일 싸이즈도 10k로 반영하였습니다.

<feature> Test/test shell/runner : Runner DLL Integration 및 Test 완료

---

.gitignore
TestScript/TestCommandFactory.cpp
TestShell/App.cpp
TestShell/App.h
TestShell/TestShell.cpp
TestShell/TestShell.vcxproj
TestShell/TestShell.vcxproj.filters
TestShell/main.cpp
TestShell/shell_script.txt

Test Shell에 App Class 적용하여 인자가 있으면 Command Mode, 인자가 있으면 Runner Mode 수행하도록 개발했습니다.

<feat> Test Shell Runner Mode

---

TestShell/TestShell.cpp
TestShell/TestShell.vcxproj
TestShell/main.cpp

TC 정상 동작 확인하였습니다. 
시연할 경우 여기 사용하세요~
PR 부탁드립니다.

<test> TC Pass 확인, Build 언어 설정 변경 C/C++ 17

---

TestShell/App.cpp

Runner Mode 시작 전 flush
Test Script Case 실행 후 flush 추가

<fix> TestScript Flush

---

SSD/EraseCommand.cpp
SSD/EraseCommand.h
SSD/WriteCommand.cpp
SSD/WriteCommand.h

- the command from command buffer is not clear

<bugfix>  fix LBA offset error
